<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use App\Models\Page\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Product::factory(100)->create();
        Product::create([
            'name' => 'Licuado de frutilla',
            'slug' => Str::slug('Licuado de frutilla'),
            'price_original' => 1100,
            'price_seller' => 1100,
            'quantity' => 0,
            'image_hero' => 'cafe_08.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de chocolate',
            'slug' => Str::slug('Licuado de chocolate'),
            'price_original' => 1100,
            'price_seller' => 1100,
            'quantity' => 0,
            'image_hero' => 'cafe_09.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de limon',
            'slug' => Str::slug('Licuado de limon'),
            'price_original' => 1100,
            'price_seller' => 1100,
            'quantity' => 0,
            'image_hero' => 'cafe_10.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de multifruta',
            'slug' => Str::slug('Licuado de multifruta'),
            'price_original' => 1100,
            'price_seller' => 1100,
            'quantity' => 0,
            'image_hero' => 'cafe_11.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de multifruta',
            'slug' => Str::slug('Licuado de multifruta'),
            'price_original' => 1100,
            'price_seller' => 1100,
            'quantity' => 0,
            'image_hero' => 'cafe_12.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de con chispas de chocolate',
            'slug' => Str::slug('Licuado de con chispas de chocolate'),
            'price_original' => 1100,
            'price_seller' => 1100,
            'quantity' => 0,
            'image_hero' => 'cafe_13.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de pistacho',
            'slug' => Str::slug('Licuado de pistacho'),
            'price_original' => 1100,
            'price_seller' => 1100,
            'quantity' => 0,
            'image_hero' => 'cafe_14.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de mix',
            'slug' => Str::slug('Licuado de mix'),
            'price_original' => 1100,
            'price_seller' => 1100,
            'quantity' => 0,
            'image_hero' => 'cafe_07.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de frutilla',
            'slug' => Str::slug('Cafe de frutilla'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'cafe_01.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 2,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de chocolate',
            'slug' => Str::slug('Cafe de chocolate'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'cafe_02.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 2,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de limon',
            'slug' => Str::slug('Cafe de limon'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'cafe_03.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 2,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de multifruta',
            'slug' => Str::slug('Cafe de multifruta'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'cafe_04.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 2,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de con chispas de chocolate',
            'slug' => Str::slug('Cafe de con chispas de chocolate'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'cafe_05.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 2,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de pistacho',
            'slug' => Str::slug('Cafe de pistacho'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'cafe_06.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 2,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de mix',
            'slug' => Str::slug('Cafe de mix'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'cafe_07.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 2,
            'level_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);

        Product::create([
            'name' => 'Torta de frutilla',
            'slug' => Str::slug('Torta de frutilla'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'pastel_01.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de chocolate',
            'slug' => Str::slug('Torta de chocolate'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'pastel_02.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de limon',
            'slug' => Str::slug('Torta de limon'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'pastel_03.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de multifruta',
            'slug' => Str::slug('Torta de multifruta'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'pastel_04.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de con chispas de chocolate',
            'slug' => Str::slug('Torta de con chispas de chocolate'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'pastel_05.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de pistacho',
            'slug' => Str::slug('Torta de pistacho'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'pastel_06.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Galleta de frutilla',
            'slug' => Str::slug('Galleta de frutilla'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'galletas_01.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de chocolate',
            'slug' => Str::slug('Galleta de chocolate'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'galletas_02.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de limon',
            'slug' => Str::slug('Galleta de limon'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'galletas_03.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de multifruta',
            'slug' => Str::slug('Galleta de multifruta'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'galletas_04.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de con chispas de chocolate',
            'slug' => Str::slug('Galleta de con chispas de chocolate'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'galletas_05.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de pistacho',
            'slug' => Str::slug('Galleta de pistacho'),
            'price_original' => 1500,
            'price_seller' => 1500,
            'quantity' => 0,
            'image_hero' => 'galletas_06.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Donas de frutilla',
            'slug' => Str::slug('Donas de frutilla'),
            'price_original' => 750,
            'price_seller' => 750,
            'quantity' => 0,
            'image_hero' => 'donas_01.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de chocolate',
            'slug' => Str::slug('Donas de chocolate'),
            'price_original' => 750,
            'price_seller' => 750,
            'quantity' => 0,
            'image_hero' => 'donas_02.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de limon',
            'slug' => Str::slug('Donas de limon'),
            'price_original' => 750,
            'price_seller' => 750,
            'quantity' => 0,
            'image_hero' => 'donas_03.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de multifruta',
            'slug' => Str::slug('Donas de multifruta'),
            'price_original' => 750,
            'price_seller' => 750,
            'quantity' => 0,
            'image_hero' => 'donas_04.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de con chispas de chocolate',
            'slug' => Str::slug('Donas de con chispas de chocolate'),
            'price_original' => 750,
            'price_seller' => 750,
            'quantity' => 0,
            'image_hero' => 'donas_05.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de pistacho',
            'slug' => Str::slug('Donas de pistacho'),
            'price_original' => 750,
            'price_seller' => 750,
            'quantity' => 0,
            'image_hero' => 'donas_06.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de mix',
            'slug' => Str::slug('Donas de mix'),
            'price_original' => 750,
            'price_seller' => 750,
            'quantity' => 0,
            'image_hero' => 'donas_07.jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'level_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
    }
}
