<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use App\Models\Page\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Product::factory(100)->create();
        Product::create([
            'name' => 'Licuado de frutilla',
            'slug' => Str::slug('Licuado de frutilla'),
            'price_original' => 1100,
            'price_seller' => 1000,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (1).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de chocolate',
            'slug' => Str::slug('Licuado de chocolate'),
            'price_original' => 1100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (2).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de limon',
            'slug' => Str::slug('Licuado de limon'),
            'price_original' => 1100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (3).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de multifruta',
            'slug' => Str::slug('Licuado de multifruta'),
            'price_original' => 1100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (4).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de multifruta',
            'slug' => Str::slug('Licuado de multifruta'),
            'price_original' => 1100,
            'price_seller' => 890,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (5).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de con chispas de chocolate',
            'slug' => Str::slug('Licuado de con chispas de chocolate'),
            'price_original' => 1100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (6).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Cafe de frutilla',
            'slug' => Str::slug('Cafe de frutilla'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (1).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de chocolate',
            'slug' => Str::slug('Cafe de chocolate'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (2).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de limon',
            'slug' => Str::slug('Cafe de limon'),
            'price_original' => 1500,
            'price_seller' => 1200,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (3).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de multifruta',
            'slug' => Str::slug('Cafe de multifruta'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (4).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de con chispas de chocolate',
            'slug' => Str::slug('Cafe de con chispas de chocolate'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (5).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de pistacho',
            'slug' => Str::slug('Cafe de pistacho'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (6).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de mix',
            'slug' => Str::slug('Cafe de mix'),
            'price_original' => 1500,
            'price_seller' => 1350,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (7).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe puro',
            'slug' => Str::slug('Cafe puro'),
            'price_original' => 1500,
            'price_seller' => 1350,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (8).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);

        Product::create([
            'name' => 'Galleta de frutilla',
            'slug' => Str::slug('Galleta de frutilla'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (1).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de chocolate',
            'slug' => Str::slug('Galleta de chocolate'),
            'price_original' => 1500,
            'price_seller' => 1200,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (2).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de limon',
            'slug' => Str::slug('Galleta de limon'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (3).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de multifruta',
            'slug' => Str::slug('Galleta de multifruta'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (4).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de con chispas de chocolate',
            'slug' => Str::slug('Galleta de con chispas de chocolate'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (5).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de pistacho',
            'slug' => Str::slug('Galleta de pistacho'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (6).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);

        Product::create([
            'name' => 'Torta de frutilla',
            'slug' => Str::slug('Torta de frutilla'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'torta (1).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de chocolate',
            'slug' => Str::slug('Torta de chocolate'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'torta (2).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de limon',
            'slug' => Str::slug('Torta de limon'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'torta (3).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de multifruta',
            'slug' => Str::slug('Torta de multifruta'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'torta (4).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de con chispas de chocolate',
            'slug' => Str::slug('Torta de con chispas de chocolate'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'torta (5).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'user_id' => 2,
            'company_id' => 2,
        ]);



        Product::create([
            'name' => 'Donas de frutilla',
            'slug' => Str::slug('Donas de frutilla'),
            'price_original' => 750,
            'price_seller' => 450,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (1).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de chocolate',
            'slug' => Str::slug('Donas de chocolate'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (2).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de limon',
            'slug' => Str::slug('Donas de limon'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (3).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de multifruta',
            'slug' => Str::slug('Donas de multifruta'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (4).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de con chispas de chocolate',
            'slug' => Str::slug('Donas de con chispas de chocolate'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (5).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de pistacho',
            'slug' => Str::slug('Donas de pistacho'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (6).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de mix',
            'slug' => Str::slug('Donas de mix'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (7).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Capuchino de mix',
            'slug' => Str::slug('Capuchino de mix'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'capuchino (1).jpg',
            'description' => 'descripcion del capuchino',
            'status' => 1,
            'category_id' => 6,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Capuchino de latex',
            'slug' => Str::slug('Capuchino de latex'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'capuchino (2).jpg',
            'description' => 'descripcion del capuchino',
            'status' => 1,
            'category_id' => 6,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Capuchino de doble',
            'slug' => Str::slug('Capuchino de doble'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'capuchino (3).jpg',
            'description' => 'descripcion del capuchino',
            'status' => 1,
            'category_id' => 6,
            'user_id' => 2,
            'company_id' => 2,
        ]);



        Product::create([
            'name' => 'Cheesse cake de frutilla',
            'slug' => Str::slug('Cheesse cake de frutilla'),
            'price_original' => 750,
            'price_seller' => 450,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (1).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cheesse cake de chocolate',
            'slug' => Str::slug('Cheesse cake de chocolate'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (2).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cheesse cake de limon',
            'slug' => Str::slug('Cheesse cake de limon'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (3).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cheesse cake de multifruta',
            'slug' => Str::slug('Cheesse cake de multifruta'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (4).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cheesse cake de con chispas de chocolate',
            'slug' => Str::slug('Cheesse cake de con chispas de chocolate'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (5).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cheesse cake de pistacho',
            'slug' => Str::slug('Cheesse cake de pistacho'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (6).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Medialuna salada',
            'slug' => Str::slug('Medialuna salada'),
            'price_original' => 750,
            'price_seller' => 450,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'medialuna (1).jpg',
            'description' => 'Descripcion de las medialunas',
            'status' => 1,
            'category_id' => 8,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Medialuna dulce',
            'slug' => Str::slug('Medialuna dulce'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'medialuna (2).jpg',
            'description' => 'Descripcion de las medialunas',
            'status' => 1,
            'category_id' => 8,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Medialuna dulce XL',
            'slug' => Str::slug('Medialuna dulce XL'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'medialuna (3).jpg',
            'description' => 'Descripcion de las medialunas',
            'status' => 1,
            'category_id' => 8,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Te de hiervas',
            'slug' => Str::slug('Te de hiervas'),
            'price_original' => 750,
            'price_seller' => 450,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'te (1).jpg',
            'description' => 'Descripcion del te',
            'status' => 1,
            'category_id' => 9,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Te de miel con menta',
            'slug' => Str::slug('Te de miel con menta'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'te (2).jpg',
            'description' => 'Descripcion del te',
            'status' => 1,
            'category_id' => 9,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Exprimido de naranja',
            'slug' => Str::slug('Exprimido de naranja'),
            'price_original' => 750,
            'price_seller' => 450,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'exprimido (1).jpg',
            'description' => 'Descripcion del exprimido',
            'status' => 1,
            'category_id' => 10,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Exprimido de limonada',
            'slug' => Str::slug('Exprimido de limonada'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'exprimido (2).jpg',
            'description' => 'Descripcion del exprimido',
            'status' => 1,
            'category_id' => 10,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Exprimido de pera',
            'slug' => Str::slug('Exprimido de pera'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'exprimido (3).jpg',
            'description' => 'Descripcion del exprimido',
            'status' => 1,
            'category_id' => 10,
            'user_id' => 2,
            'company_id' => 2,
        ]);
    }
}
