<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use App\Models\Page\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Product::factory(100)->create();
        Product::create([
            'name' => 'Licuado de frutilla',
            'slug' => Str::slug('Licuado de frutilla'),
            'price_original' => 1100,
            'price_seller' => 1000,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (1).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de chocolate',
            'slug' => Str::slug('Licuado de chocolate'),
            'price_original' => 1100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (2).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de limon',
            'slug' => Str::slug('Licuado de limon'),
            'price_original' => 1100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (3).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de multifruta',
            'slug' => Str::slug('Licuado de multifruta'),
            'price_original' => 1100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (4).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de multifruta',
            'slug' => Str::slug('Licuado de multifruta'),
            'price_original' => 1100,
            'price_seller' => 890,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (5).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Licuado de con chispas de chocolate',
            'slug' => Str::slug('Licuado de con chispas de chocolate'),
            'price_original' => 1100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'batido (6).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 1,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Cafe de frutilla',
            'slug' => Str::slug('Cafe de frutilla'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (1).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de chocolate',
            'slug' => Str::slug('Cafe de chocolate'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (2).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de limon',
            'slug' => Str::slug('Cafe de limon'),
            'price_original' => 1500,
            'price_seller' => 1200,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (3).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de multifruta',
            'slug' => Str::slug('Cafe de multifruta'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (4).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de con chispas de chocolate',
            'slug' => Str::slug('Cafe de con chispas de chocolate'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (5).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de pistacho',
            'slug' => Str::slug('Cafe de pistacho'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (6).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe de mix',
            'slug' => Str::slug('Cafe de mix'),
            'price_original' => 1500,
            'price_seller' => 1350,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (7).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cafe puro',
            'slug' => Str::slug('Cafe puro'),
            'price_original' => 1500,
            'price_seller' => 1350,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cafe (8).jpg',
            'description' => 'Descripcion para el cafe',
            'status' => 1,
            'category_id' => 2,
            'user_id' => 2,
            'company_id' => 2,
        ]);

        Product::create([
            'name' => 'Galleta de frutilla',
            'slug' => Str::slug('Galleta de frutilla'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (1).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de chocolate',
            'slug' => Str::slug('Galleta de chocolate'),
            'price_original' => 1500,
            'price_seller' => 1200,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (2).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de limon',
            'slug' => Str::slug('Galleta de limon'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (3).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de multifruta',
            'slug' => Str::slug('Galleta de multifruta'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (4).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de con chispas de chocolate',
            'slug' => Str::slug('Galleta de con chispas de chocolate'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (5).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Galleta de pistacho',
            'slug' => Str::slug('Galleta de pistacho'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'galleta (6).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 3,
            'user_id' => 2,
            'company_id' => 2,
        ]);

        Product::create([
            'name' => 'Torta de frutilla',
            'slug' => Str::slug('Torta de frutilla'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'torta (1).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de chocolate',
            'slug' => Str::slug('Torta de chocolate'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'torta (2).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de limon',
            'slug' => Str::slug('Torta de limon'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'torta (3).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de multifruta',
            'slug' => Str::slug('Torta de multifruta'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'torta (4).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Torta de con chispas de chocolate',
            'slug' => Str::slug('Torta de con chispas de chocolate'),
            'price_original' => 1500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'torta (5).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 4,
            'user_id' => 2,
            'company_id' => 2,
        ]);



        Product::create([
            'name' => 'Donas de frutilla',
            'slug' => Str::slug('Donas de frutilla'),
            'price_original' => 750,
            'price_seller' => 450,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (1).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de chocolate',
            'slug' => Str::slug('Donas de chocolate'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (2).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de limon',
            'slug' => Str::slug('Donas de limon'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (3).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de multifruta',
            'slug' => Str::slug('Donas de multifruta'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (4).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de con chispas de chocolate',
            'slug' => Str::slug('Donas de con chispas de chocolate'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (5).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de pistacho',
            'slug' => Str::slug('Donas de pistacho'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (6).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Donas de mix',
            'slug' => Str::slug('Donas de mix'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'dona (7).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 5,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Capuchino de mix',
            'slug' => Str::slug('Capuchino de mix'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'capuchino (1).jpg',
            'description' => 'descripcion del capuchino',
            'status' => 1,
            'category_id' => 6,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Capuchino de latex',
            'slug' => Str::slug('Capuchino de latex'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'capuchino (2).jpg',
            'description' => 'descripcion del capuchino',
            'status' => 1,
            'category_id' => 6,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Capuchino de doble',
            'slug' => Str::slug('Capuchino de doble'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'capuchino (3).jpg',
            'description' => 'descripcion del capuchino',
            'status' => 1,
            'category_id' => 6,
            'user_id' => 2,
            'company_id' => 2,
        ]);



        Product::create([
            'name' => 'Cheesse cake de frutilla',
            'slug' => Str::slug('Cheesse cake de frutilla'),
            'price_original' => 750,
            'price_seller' => 450,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (1).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cheesse cake de chocolate',
            'slug' => Str::slug('Cheesse cake de chocolate'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (2).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cheesse cake de limon',
            'slug' => Str::slug('Cheesse cake de limon'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (3).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cheesse cake de multifruta',
            'slug' => Str::slug('Cheesse cake de multifruta'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (4).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cheesse cake de con chispas de chocolate',
            'slug' => Str::slug('Cheesse cake de con chispas de chocolate'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (5).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Cheesse cake de pistacho',
            'slug' => Str::slug('Cheesse cake de pistacho'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'cheesecake (6).jpg',
            'description' => 'Descripcion del licuado',
            'status' => 1,
            'category_id' => 7,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Medialuna salada',
            'slug' => Str::slug('Medialuna salada'),
            'price_original' => 750,
            'price_seller' => 450,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'medialuna (1).jpg',
            'description' => 'Descripcion de las medialunas',
            'status' => 1,
            'category_id' => 8,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Medialuna dulce',
            'slug' => Str::slug('Medialuna dulce'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'medialuna (2).jpg',
            'description' => 'Descripcion de las medialunas',
            'status' => 1,
            'category_id' => 8,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Medialuna dulce XL',
            'slug' => Str::slug('Medialuna dulce XL'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'medialuna (3).jpg',
            'description' => 'Descripcion de las medialunas',
            'status' => 1,
            'category_id' => 8,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Te de hiervas',
            'slug' => Str::slug('Te de hiervas'),
            'price_original' => 750,
            'price_seller' => 450,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'te (1).jpg',
            'description' => 'Descripcion del te',
            'status' => 1,
            'category_id' => 9,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Te de miel con menta',
            'slug' => Str::slug('Te de miel con menta'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'te (2).jpg',
            'description' => 'Descripcion del te',
            'status' => 1,
            'category_id' => 9,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        Product::create([
            'name' => 'Exprimido de naranja',
            'slug' => Str::slug('Exprimido de naranja'),
            'price_original' => 750,
            'price_seller' => 450,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'exprimido (1).jpg',
            'description' => 'Descripcion del exprimido',
            'status' => 1,
            'category_id' => 10,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Exprimido de limonada',
            'slug' => Str::slug('Exprimido de limonada'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'exprimido (2).jpg',
            'description' => 'Descripcion del exprimido',
            'status' => 1,
            'category_id' => 10,
            'user_id' => 2,
            'company_id' => 2,
        ]);
        Product::create([
            'name' => 'Exprimido de pera',
            'slug' => Str::slug('Exprimido de pera'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/2/products/',
            'image_hero' => 'exprimido (3).jpg',
            'description' => 'Descripcion del exprimido',
            'status' => 1,
            'category_id' => 10,
            'user_id' => 2,
            'company_id' => 2,
        ]);


        // el favorito
        // id 11
        Product::create([
            'name' => 'Coca cola',
            'slug' => Str::slug('Coca cola'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'gaseosa (1).jpg',
            'description' => 'Descripcion de la gaseosa',
            'status' => 1,
            'category_id' => 11,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Sprite',
            'slug' => Str::slug('Sprite'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'gaseosa (2).jpg',
            'description' => 'Descripcion de la gaseosa',
            'status' => 1,
            'category_id' => 11,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Fanta',
            'slug' => Str::slug('Fanta'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'gaseosa (3).jpg',
            'description' => 'Descripcion de la gaseosa',
            'status' => 1,
            'category_id' => 11,
            'user_id' => 3,
            'company_id' => 3,
        ]);

        // id 12
        Product::create([
            'name' => 'Agua savorizada',
            'slug' => Str::slug('Agua savorizada'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'jugo (1).jpg',
            'description' => 'Gustos de pomelo, naranja y pera',
            'status' => 1,
            'category_id' => 12,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Agua',
            'slug' => Str::slug('Agua'),
            'price_original' => 750,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'jugo (2).jpg',
            'description' => 'Agua natural',
            'status' => 1,
            'category_id' => 12,
            'user_id' => 3,
            'company_id' => 3,
        ]);

        // id 13
        Product::create([
            'name' => 'Vino malbec',
            'slug' => Str::slug('Vino malbec'),
            'price_original' => 2300,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'vino (1).jpg',
            'description' => 'Descripcion de la vino',
            'status' => 1,
            'category_id' => 13,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Vino blanco',
            'slug' => Str::slug('Vino blanco'),
            'price_original' => 2300,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'vino (2).jpg',
            'description' => 'Descripcion de la vino',
            'status' => 1,
            'category_id' => 13,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Vino tinto',
            'slug' => Str::slug('Vino tinto'),
            'price_original' => 2300,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'vino (3).jpg',
            'description' => 'Descripcion de la vino',
            'status' => 1,
            'category_id' => 13,
            'user_id' => 3,
            'company_id' => 3,
        ]);

        // id 14
        Product::create([
            'name' => 'Pizza fugazzeta',
            'slug' => Str::slug('Pizza fugazzeta'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (1).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Pizza napo',
            'slug' => Str::slug('Pizza napo'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (2).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Pizza de pollo',
            'slug' => Str::slug('Pizza de pollo'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (3).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Pizza de verdura',
            'slug' => Str::slug('Pizza de verdura'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (4).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Pizza de 4 quesos',
            'slug' => Str::slug('Pizza de 4 quesos'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (5).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Pizza con champignones',
            'slug' => Str::slug('Pizza con champignones'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (6).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Pizza calabresa',
            'slug' => Str::slug('Pizza calabresa'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (7).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Pizza picante',
            'slug' => Str::slug('Pizza picante'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (8).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Pizza completa',
            'slug' => Str::slug('Pizza completa'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (9).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Pizza de pecceto',
            'slug' => Str::slug('Pizza de pecceto'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (10).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Pizza comun',
            'slug' => Str::slug('Pizza comun'),
            'price_original' => 4900,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'pizzas (11).jpg',
            'description' => 'Descripcion de la pizza',
            'status' => 1,
            'category_id' => 14,
            'user_id' => 3,
            'company_id' => 3,
        ]);

        // id 15
        Product::create([
            'name' => 'Hamburguesa',
            'slug' => Str::slug('Hamburguesa'),
            'price_original' => 3500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'hamburguesa (1).jpg',
            'description' => 'Descripcion de la hamburguesa',
            'status' => 1,
            'category_id' => 15,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Hamburguesa doble',
            'slug' => Str::slug('Hamburguesa doble'),
            'price_original' => 3500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'hamburguesa (2).jpg',
            'description' => 'Descripcion de la hamburguesa',
            'status' => 1,
            'category_id' => 15,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Hamburguesa cheddar',
            'slug' => Str::slug('Hamburguesa cheddar'),
            'price_original' => 3500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'hamburguesa (3).jpg',
            'description' => 'Descripcion de la hamburguesa',
            'status' => 1,
            'category_id' => 15,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Hamburguesa a la panceta',
            'slug' => Str::slug('Hamburguesa a la panceta'),
            'price_original' => 3500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'hamburguesa (4).jpg',
            'description' => 'Descripcion de la hamburguesa',
            'status' => 1,
            'category_id' => 15,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Hamburguesa veggie',
            'slug' => Str::slug('Hamburguesa veggie'),
            'price_original' => 3500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'hamburguesa (5).jpg',
            'description' => 'Descripcion de la hamburguesa',
            'status' => 1,
            'category_id' => 15,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Hamburguesa mac',
            'slug' => Str::slug('Hamburguesa mac'),
            'price_original' => 3500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'hamburguesa (6).jpg',
            'description' => 'Descripcion de la hamburguesa',
            'status' => 1,
            'category_id' => 15,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Hamburguesa napo',
            'slug' => Str::slug('Hamburguesa napo'),
            'price_original' => 3500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'hamburguesa (7).jpg',
            'description' => 'Descripcion de la hamburguesa',
            'status' => 1,
            'category_id' => 15,
            'user_id' => 3,
            'company_id' => 3,
        ]);

        // id 16
        Product::create([
            'name' => 'Milanesa al limon',
            'slug' => Str::slug('Milanesa al limon'),
            'price_original' => 4200,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'milanesa (1).jpg',
            'description' => 'Descripcion de la milanesa',
            'status' => 1,
            'category_id' => 16,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Milanesa napo',
            'slug' => Str::slug('Milanesa napo'),
            'price_original' => 4200,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'milanesa (2).jpg',
            'description' => 'Descripcion de la milanesa',
            'status' => 1,
            'category_id' => 16,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Milanesa a caballo',
            'slug' => Str::slug('Milanesa a caballo'),
            'price_original' => 4200,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'milanesa (3).jpg',
            'description' => 'Descripcion de la milanesa',
            'status' => 1,
            'category_id' => 16,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Milanesa con cheddar',
            'slug' => Str::slug('Milanesa con cheddar'),
            'price_original' => 4200,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'milanesa (4).jpg',
            'description' => 'Descripcion de la milanesa',
            'status' => 1,
            'category_id' => 16,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Milanesa fugazza',
            'slug' => Str::slug('Milanesa fugazza'),
            'price_original' => 4200,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'milanesa (5).jpg',
            'description' => 'Descripcion de la milanesa',
            'status' => 1,
            'category_id' => 16,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Milanesa XL',
            'slug' => Str::slug('Milanesa XL'),
            'price_original' => 4200,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'milanesa (6).jpg',
            'description' => 'Descripcion de la milanesa',
            'status' => 1,
            'category_id' => 16,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Milanesa con roque',
            'slug' => Str::slug('Milanesa con roque'),
            'price_original' => 4200,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'milanesa (7).jpg',
            'description' => 'Descripcion de la milanesa',
            'status' => 1,
            'category_id' => 16,
            'user_id' => 3,
            'company_id' => 3,
        ]);

        // id 17
        Product::create([
            'name' => 'Papas fritas',
            'slug' => Str::slug('Papas fritas'),
            'price_original' => 2500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'papas (1).jpg',
            'description' => 'Descripcion de las papas',
            'status' => 1,
            'category_id' => 17,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Papas fritas al provenzal',
            'slug' => Str::slug('Papas fritas al provenzal'),
            'price_original' => 2500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'papas (2).jpg',
            'description' => 'Descripcion de las papas',
            'status' => 1,
            'category_id' => 17,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Papas fritas cheddar',
            'slug' => Str::slug('Papas fritas cheddar'),
            'price_original' => 2500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'papas (3).jpg',
            'description' => 'Descripcion de las papas',
            'status' => 1,
            'category_id' => 17,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Papas fritas picantes',
            'slug' => Str::slug('Papas fritas picantes'),
            'price_original' => 2500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'papas (4).jpg',
            'description' => 'Descripcion de las papas',
            'status' => 1,
            'category_id' => 17,
            'user_id' => 3,
            'company_id' => 3,
        ]);

        // id 18
        Product::create([
            'name' => 'Picada',
            'slug' => Str::slug('Picada'),
            'price_original' => 2500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'picada (1).jpg',
            'description' => 'Descripcion de la picada',
            'status' => 1,
            'category_id' => 18,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Picada para 2',
            'slug' => Str::slug('Picada para 2'),
            'price_original' => 2500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'picada (2).jpg',
            'description' => 'Descripcion de la picada',
            'status' => 1,
            'category_id' => 18,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Picada completa',
            'slug' => Str::slug('Picada completa'),
            'price_original' => 2500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'picada (3).jpg',
            'description' => 'Descripcion de la picada',
            'status' => 1,
            'category_id' => 18,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Picada mini',
            'slug' => Str::slug('Picada mini'),
            'price_original' => 2500,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'picada (4).jpg',
            'description' => 'Descripcion de la picada',
            'status' => 1,
            'category_id' => 18,
            'user_id' => 3,
            'company_id' => 3,
        ]);

        // id 19
        Product::create([
            'name' => 'Tallarines',
            'slug' => Str::slug('Tallarines'),
            'price_original' => 5100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'tallarin (1).jpg',
            'description' => 'Descripcion del tallarin',
            'status' => 1,
            'category_id' => 19,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Tallarines al pesto',
            'slug' => Str::slug('Tallarines al pesto'),
            'price_original' => 5100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'tallarin (2).jpg',
            'description' => 'Descripcion del tallarin',
            'status' => 1,
            'category_id' => 19,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Tallarines con crema',
            'slug' => Str::slug('Tallarines con crema'),
            'price_original' => 5100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'tallarin (3).jpg',
            'description' => 'Descripcion del tallarin',
            'status' => 1,
            'category_id' => 19,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Tallarines a la bolognesa',
            'slug' => Str::slug('Tallarines a la bolognesa'),
            'price_original' => 5100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'tallarin (4).jpg',
            'description' => 'Descripcion del tallarin',
            'status' => 1,
            'category_id' => 19,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Tallarines con especias',
            'slug' => Str::slug('Tallarines con especias'),
            'price_original' => 5100,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'tallarin (5).jpg',
            'description' => 'Descripcion del tallarin',
            'status' => 1,
            'category_id' => 19,
            'user_id' => 3,
            'company_id' => 3,
        ]);

        // id 20
        Product::create([
            'name' => 'Sandwich con lomito',
            'slug' => Str::slug('Sandwich con lomito'),
            'price_original' => 3600,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'sandwich (1).jpg',
            'description' => 'Descripcion del sandwich',
            'status' => 1,
            'category_id' => 20,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Sandwich veggie',
            'slug' => Str::slug('Sandwich veggie'),
            'price_original' => 3600,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'sandwich (2).jpg',
            'description' => 'Descripcion del sandwich',
            'status' => 1,
            'category_id' => 20,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Sandwich fresco',
            'slug' => Str::slug('Sandwich fresco'),
            'price_original' => 3600,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'sandwich (3).jpg',
            'description' => 'Descripcion del sandwich',
            'status' => 1,
            'category_id' => 20,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Sandwich con verduras',
            'slug' => Str::slug('Sandwich con verduras'),
            'price_original' => 3600,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'sandwich (4).jpg',
            'description' => 'Descripcion del sandwich',
            'status' => 1,
            'category_id' => 20,
            'user_id' => 3,
            'company_id' => 3,
        ]);

        // id 21
        Product::create([
            'name' => 'Cheesse cake',
            'slug' => Str::slug('Cheesse cake'),
            'price_original' => 4300,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'postre (1).jpg',
            'description' => 'Descripcion del postre',
            'status' => 1,
            'category_id' => 21,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Cheesse cake dulce',
            'slug' => Str::slug('Cheesse cake dulce'),
            'price_original' => 4300,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'postre (2).jpg',
            'description' => 'Descripcion del postre',
            'status' => 1,
            'category_id' => 21,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Lemon Pie',
            'slug' => Str::slug('Lemon Pie'),
            'price_original' => 4300,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'postre (3).jpg',
            'description' => 'Descripcion del postre',
            'status' => 1,
            'category_id' => 21,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Mousse de chocolate',
            'slug' => Str::slug('Mousse de chocolate'),
            'price_original' => 4300,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'postre (4).jpg',
            'description' => 'Descripcion del postre',
            'status' => 1,
            'category_id' => 21,
            'user_id' => 3,
            'company_id' => 3,
        ]);
        Product::create([
            'name' => 'Cheesse cake XL',
            'slug' => Str::slug('Cheesse cake XL'),
            'price_original' => 4300,
            'price_seller' => 0,
            'quantity' => 0,
            'image_hero_uri' => 'archives/images/3/products/',
            'image_hero' => 'postre (5).jpg',
            'description' => 'Descripcion del postre',
            'status' => 1,
            'category_id' => 21,
            'user_id' => 3,
            'company_id' => 3,
        ]);
    }
}
